# Generated by Django 6.0.7 on 2026-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('BBA', 'Business Administration'), ('English', 'English'), ('Bangla', 'Bangla'), ('Economics', 'Economics'), ('Sociology', 'Sociology'), ('Political Science', 'Political Science'), ('Philosophy', 'Philosophy'), ('History', 'History'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Inter-Science', 'Inter-Science'), ('Inter-Commerce', 'Inter-Commerce'), ('Inter-Arts', 'Inter-Arts'), ('All', 'All')], default='All', max_length=100),
        ),
    ]
