# Generated by Django 6.0.7 on 2026-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('BBA', 'Business Administration'), ('English', 'English'), ('Bangla', 'Bangla'), ('Economics', 'Economics'), ('Social Work', 'Social Work'), ('Political Science', 'Political Science'), ('Islamic History & Culture', 'Islamic History & Culture'), ('Accounting', 'Accounting'), ('Finance and Banking', 'Finance and Banking'), ('Management', 'Management'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Anthropology', 'Anthropology'), ('Inter-Science', 'Inter-Science'), ('Inter-Commerce', 'Inter-Commerce'), ('Inter-Arts', 'Inter-Arts'), ('All', 'All')], default='All', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('college_admin', 'College Admin'), ('department_admin', 'Department Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_roll', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('BBA', 'Business Administration'), ('English', 'English'), ('Bangla', 'Bangla'), ('Economics', 'Economics'), ('Social Work', 'Social Work'), ('Political Science', 'Political Science'), ('Islamic History & Culture', 'Islamic History & Culture'), ('Accounting', 'Accounting'), ('Finance and Banking', 'Finance and Banking'), ('Management', 'Management'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Anthropology', 'Anthropology'), ('Inter-Science', 'Inter-Science'), ('Inter-Commerce', 'Inter-Commerce'), ('Inter-Arts', 'Inter-Arts'), ('All', 'All')], max_length=100)),
                ('session', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_roll', 'department'), name='unique_student_department_roll')],
            },
        ),
    ]
